# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_h1Ni5IBnI6qfCvbT4ENMOmKK-W_IlJ
"""

from google.colab import files
uploaded=files.upload()

"""### Upload and Extract Dataset

The `FileNotFoundError` indicates that the directory `/content/leapGestRecog` does not exist. Please upload your dataset, typically a `.zip` file (e.g., `leapGestRecog.zip`), using the cell below. After uploading, the code will extract it to the correct location.
"""

import zipfile
import os

zip_ref=zipfile.ZipFile('/content/leapGestRecog.zip.zip','r')
zip_ref.extractall('/content/')
zip_ref.close()


print("Contents of /content/ after extraction:")
print(os.listdir('/content/'))


import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GlobalAveragePooling2D,Dense,Dropout

datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    validation_split=0.2,
    horizontal_flip=True,
    zoom_range=0.1
)

train_data = datagen.flow_from_directory(
    '/content/augmented_data',
    target_size=(128,128),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

validation_data = datagen.flow_from_directory(
    '/content/augmented_data',
    target_size=(128,128),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(128,128,3)
)
base_model.trainable=False

import matplotlib.pyplot as plt

model=Sequential([
base_model,
GlobalAveragePooling2D(),
Dense(128,activation='relu'),
Dropout(0.3),
Dense(train_data.num_classes,activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
history=model.fit(
    train_data,
    epochs=10,
    validation_data=validation_data
)


plt.plot(history.history['accuracy'],label='accuracy')
plt.plot(history.history['val_accuracy'],label='val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')

plt.legend( ['Training','Validation'])
plt.title('Gesture Recognition Accuracy')
plt.show()

model.save('/content/gesture_model.keras')